name: tests

on:
  pull_request:
  push:
    paths:
      - '**.py'
      - '.github/workflows/tests.yml'
      - 'docker-test.sh'
  schedule:
    # Test master every Saturday at midnight to verify dependencies
    - cron:  '0 0 * * 6'

jobs:
  flake8:
    name: Flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set Up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8
      - name: Check
        run: python -m flake8
  test:
    name: Test
    needs: flake8
    runs-on: ubuntu-latest
    container: aiudirog/aiohappybase-test-env:latest
    strategy:
      matrix:
        python: ['3.6', '3.7', '3.8', '3.9']
        client: ['socket', 'http']
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        env:
          PYTHON_VERSION: ${{ matrix.python }}
          AIOHAPPYBASE_CLIENT: ${{ matrix.client }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: ./docker-test.sh
