name: Run Tests

on:
  pull_request:
  push:
    paths:
      - '**.py'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.6', '3.7']
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        uses: ./.github/actions/test
        env:
          PYTHON_VERSION: ${{ matrix.python }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
